# Sample config variables 

# This is your API token
cloudflare_token: abc123def456

# This is your account hash
# https://api.cloudflare.com/client/v4/accounts/#{cloudflare_account}/images/v1"
#                                               ^^^^^^^^^^^^^^^^^^^^
cloudflare_account: zyxabc123def098klm

# This is the account hash that goes in your cloudflare urls -- see the docs 
cloudflare_account_hash: 